// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clusters": {
            "get": {
                "description": "List all Elasticsearch clusters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "List all clusters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ClusterStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Elasticsearch cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Create a new cluster",
                "parameters": [
                    {
                        "description": "Cluster configuration",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an Elasticsearch cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Delete a cluster",
                "parameters": [
                    {
                        "description": "Cluster deletion info",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/clusters/scale": {
            "post": {
                "description": "Scale an Elasticsearch cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Scale a cluster",
                "parameters": [
                    {
                        "description": "Cluster scaling info",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ScaleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ClusterStatus": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dimension": {
                    "type": "integer"
                },
                "disk_usage": {
                    "type": "number"
                },
                "gpu_count": {
                    "type": "integer"
                },
                "memory_usage": {
                    "type": "number"
                },
                "namespace": {
                    "type": "string"
                },
                "qps": {
                    "type": "number"
                },
                "replicas": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "vector_count": {
                    "type": "integer"
                }
            }
        },
        "main.CreateRequest": {
            "type": "object",
            "properties": {
                "cpu_limit": {
                    "type": "string"
                },
                "cpu_request": {
                    "type": "string"
                },
                "dimension": {
                    "type": "integer"
                },
                "disk_size": {
                    "type": "string"
                },
                "gitlab_url": {
                    "type": "string"
                },
                "gpu_count": {
                    "type": "integer"
                },
                "index_limit": {
                    "type": "integer"
                },
                "mem_limit": {
                    "type": "string"
                },
                "mem_request": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer"
                },
                "service_name": {
                    "type": "string"
                },
                "tenant_org_id": {
                    "description": "租户组织ID（多租户隔离）",
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "vector_count": {
                    "type": "integer"
                }
            }
        },
        "main.DeleteRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                }
            }
        },
        "main.ScaleRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ES Serverless Manager API",
	Description:      "This is a server for managing Elasticsearch Serverless clusters.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
